spring.application.name=Auth-service


# =========================
# APP CONFIGURATION
# =========================
server.port=8081

# =========================
# DATABASE CONFIGURATION
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/semulateur?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA CONFIGURATION
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# KEYCLOAK CONFIGURATION
# =========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/your-realm-name
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/your-realm-name/protocol/openid-connect/certs
# =========================
# LOGGING
# =========================
logging.level.org.springframework.security=DEBUG
