version: '3.8'
services:
  auth-service2:
    build: ./auth-service2
    ports:
      - "8081:8080"
  depacking-iso-service:
    build: ./DepackingISOService
    ports:
      - "8082:8080"
  gateway-service:
    build: ./GatewayService
    ports:
      - "8083:8080"
  incident-report-service:
    build: ./IncidentReportService
    ports:
      - "8084:8080"
  monitoring-service:
    build: ./MonitoringService
    ports:
      - "8085:8080"
  notification-service:
    build: ./NotificationService
    ports:
      - "8086:8080"
  packing-iso-service:
    build: ./PackingISOService
    ports:
      - "8087:8080"
  response-iso-service:
    build: ./ResponseISOService
    ports:
      - "8088:8080"
  transaction-history-service:
    build: ./TransactionHistoryService
    ports:
      - "8089:8080" 