spring.application.name=MonitoringService

# Configuration de la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/monitoring_db
spring.datasource.username=root
spring.datasource.password=123456

# Hibernate et JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Port du serveur
server.port=8085

# Logger juste les erreurs (pas tout désactiver)
logging.level.root=ERROR


logging.level.org.hibernate.SQL=DEBUG


