import { NavItem } from './nav-item/nav-item';

export const navItems: NavItem[] = [
  {
    navCap: 'Home',
  },
  {
    displayName: 'Dashboard',
    iconName: 'layout-grid-add',
    route: '/dashboard',
  },
  {
    displayName: 'Message',
    iconName: 'message-circle',
    route: '/message',
  },
  {
    displayName: 'Transaction',
    iconName: 'list-details',
    route: '/transaction',
  },
  {
    displayName: 'Users',
    iconName: 'users',
    route: '/users',
  },
  {
    displayName: 'Logs',
    iconName: 'file-text',
    route: '/logs',
  },
  {
    displayName: 'Analytical',
    iconName: 'aperture',
    route: 'https://modernize-angular-main.netlify.app/dashboards/dashboard1',
    chip: true,
    external: true,
    chipClass: 'bg-light-secondary text-secondary',
    chipContent: 'PRO',
  },
  {
    displayName: 'eCommerce',
    iconName: 'shopping-cart',
    route: 'https://modernize-angular-main.netlify.app/dashboards/dashboard2',
    chip: true,
    external: true,
    chipClass: 'bg-light-secondary text-secondary',
    chipContent: 'PRO',
  },
  {
    navCap: 'Tables',
  },
  {
    displayName: 'Tables',
    iconName: 'layout',
    route: 'tables',
    chip: true,
    children: [
      {
        displayName: 'Basic Table',
        iconName: 'point',
        route: 'https://modernize-angular-main.netlify.app/tables/basic-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Dynamic Table',
        iconName: 'point',
        route: 'https://modernize-angular-main.netlify.app/tables/dynamic-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Expand Table',
        iconName: 'point',
        route: 'https://modernize-angular-main.netlify.app/tables/expand-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Filterable Table',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/filterable-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Footer Row Table',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/footer-row-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'HTTP Table',
        iconName: 'point',
        route: 'https://modernize-angular-main.netlify.app/tables/http-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Mix Table',
        iconName: 'point',
        route: 'https://modernize-angular-main.netlify.app/tables/mix-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Multi Header Footer',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/multi-header-footer-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Pagination Table',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/pagination-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Row Context Table',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/row-context-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Selection Table',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/selection-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Sortable Table',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/sortable-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Sticky Column',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/sticky-column-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
      {
        displayName: 'Sticky Header Footer',
        iconName: 'point',
        route:
          'https://modernize-angular-main.netlify.app/tables/sticky-header-footer-table',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
      },
    ],
  },
  {
    displayName: 'Data table',
    iconName: 'border-outer',
    route: 'https://modernize-angular-main.netlify.app/datatable/kichen-sink',
    external: true,
    chip: true,
    chipClass: 'bg-light-secondary text-secondary',
    chipContent: 'PRO',
  },
  {
    navCap: 'Auth',
  },
  {
    displayName: 'Login',
    iconName: 'login',
    route: '/authentication',
    children: [
      {
        displayName: 'Login',
        iconName: 'point',
        route: '/authentication/login',
      },
      {
        displayName: 'Side Login',
        iconName: 'point',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary', 
        chipContent: 'PRO',
        route: 'https://modernize-angular-main.netlify.app/authentication/login',
      },
    ],
  },
  {
    displayName: 'Register',
    iconName: 'user-plus',
    route: '/authentication',
    children: [
      {
        displayName: 'Register',
        iconName: 'point',
        route: '/authentication/register',
      },
      {
        displayName: 'Side Register',
        iconName: 'point',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
        route: 'https://modernize-angular-main.netlify.app/authentication/side-register',
      },
    ],
  },
  {
    displayName: 'Forgot Pwd',
    iconName: 'rotate',
    chip: true,
    route: '/authentication',
    children: [
      {
        displayName: 'Side Forgot Pwd',
        iconName: 'point',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
        route: 'https://modernize-angular-main.netlify.app/authentication/side-forgot-pwd',
      },
      {
        displayName: 'Boxed Forgot Pwd',
        iconName: 'point',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
        route: 'https://modernize-angular-main.netlify.app/authentication/boxed-forgot-pwd',
      },
    ],
  },
  {
    displayName: 'Two Steps',
    iconName: 'zoom-code',
    chip: true,
    route: '/authentication',
    children: [
      {
        displayName: 'Side Two Steps',
        iconName: 'point',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
        route: 'https://modernize-angular-main.netlify.app/authentication/side-two-steps',
      },
      {
        displayName: 'Boxed Two Steps',
        iconName: 'point',
        external: true,
        chip: true,
        chipClass: 'bg-light-secondary text-secondary',
        chipContent: 'PRO',
        route: 'https://modernize-angular-main.netlify.app/authentication/boxed-two-steps',
      },
    ],
  },
  {
    displayName: 'Error',
    iconName: 'alert-circle',
    route: 'https://modernize-angular-main.netlify.app//authentication/error',
    external: true,
    chip: true,
    chipClass: 'bg-light-secondary text-secondary',
    chipContent: 'PRO',
  },
  {
    displayName: 'Maintenance',
    iconName: 'settings',
    route: 'https://modernize-angular-main.netlify.app//authentication/maintenance',
    external: true,
    chip: true,
    chipClass: 'bg-light-secondary text-secondary',
    chipContent: 'PRO',
  },
];
