server:
  port: 8086

spring:
  application:
    name: auth-service2

  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1021072643296-n455uc8is33jfu9235jpd2ecfp396ce3.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email

  mail:
      host: smtp.gmail.com
      port: 587
      username: habibtablioua1971@gmail.com
      password: ton_mot_de_passe_ou_mot_de_passe_application
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: super-ultra-mega-long-secret-key-123456



