spring.application.name=Authservice



# Configuration de Keycloak Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/banking-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/banking-realm/protocol/openid-connect/certs

#  Configuration générale (optionnelle)
server.port=8081

#  Pour activer les logs de sécurité (utile pour debug)
logging.level.org.springframework.security=DEBUG

spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=false

