server:
  port: 8081

spring:
  application:
    name: Authservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/banking-realm
          jwk-set-uri: http://localhost:8180/realms/banking-realm/protocol/openid-connect/certs

# (Facultatif) Configuration Keycloak spécifique à certains cas
keycloak:
  realm: banking-realm
  auth-server-url: http://localhost:8180
  resource: first-client
  credentials:
    secret: Um8xGMPsKKljqfWO7xUyWPG28WQeP5j3

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
