# ========== Nom et port ==========
spring.application.name=packing-iso-service
server.port=8082

# ========== Eureka ==========
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# ========== Spring Cloud Config & Discovery ==========
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true

# ========== Autoriser override des beans ==========
spring.main.allow-bean-definition-overriding=true

# ========== Logging ==========
logging.file.name=D:/logs/iso-logs.log
logging.level.root=INFO
logging.level.org.example=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

# Format console et fichier
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

jwt.secret=super-ultra-mega-long-secret-key-123456

