spring.application.name=PackingISOService


server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.file.name=D:/logs/iso-logs.log
logging.level.root=INFO
logging.level.org.example=DEBUG

# Format optionnel
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.level.org.springframework.web.client.RestTemplate=DEBUG
