spring.application.name=eureka-server


server.port=8761


# Désactiver le config server (important pour éviter l?erreur)
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Eureka spécifique
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
