# Nom de l'application dans Eureka
spring.application.name=eureka-server

# Port du serveur Eureka
server.port=8761

# Pour désactiver la tentative de chargement depuis un config server
spring.config.import=optional:configserver:

# Désactiver le client Spring Cloud Config (sécurité en plus)
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Configuration spécifique à Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
