    # ========================
    # Application Name & Port
    # ========================
    spring.application.name=depacking-iso-service
    server.port=8083

    # ================
    # Eureka Discovery
    # ================4
    eureka.client.service-url.defaultZone=http://localhost:8761/eureka
    eureka.client.fetch-registry=true
    eureka.client.register-with-eureka=true

    # ============================
    # Spring Cloud Config Disable
    # ============================
    spring.cloud.discovery.enabled=true
jwt.secret=super-ultra-mega-long-secret-key-123456



