# Gateway Service Configuration
spring.application.name=gateway-service
server.port=8088

# JWT Configuration
jwt.secret=super-ultra-mega-long-secret-key-123456
jwt.expiration=86400000

# Eureka Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

